# Created using wingetcreate 1.6.1.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.6.0.schema.json

PackageIdentifier: SpaceWizards.RSIEdit
PackageVersion: 0.6.6
PackageLocale: en-US
Publisher: Space Wizards Federation
PackageName: RSIEdit
License: MIT
ShortDescription: RSIEdit is a GUI application for creating and editing RSI files and converting existing DMI files to the RSI format.
ManifestType: defaultLocale
ManifestVersion: 1.6.0
